#
# AUTH CONFIG — Docker local
#
auth_port=4452
auth_listen=0.0.0.0
auth_log=log/authkig.log
auth_nlive=127.0.0.1
auth_dbhost=mysql
auth_dbuser=kigadmin2
auth_dbpass=localdev
auth_dbname=kigsolidario2
