#
# AUTH CONFIG FILE
#
auth_port=4452
auth_listen=192.168.100.6
auth_log=log/authkig.log
auth_nlive=192.168.0.5;192.168.1.253;192.168.98.10
auth_dbhost=192.168.100.6
auth_dbuser=kigadmin2
auth_dbpass=mar89$an2-
auth_dbname=kigsolidario2
